"""empty message

Revision ID: 6cd67accb904
Revises: 26748a6e1977
Create Date: 2024-09-10 15:04:04.378194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd67accb904'
down_revision = '26748a6e1977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_carrusel', sa.Boolean(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('offer_carrusel')

    # ### end Alembic commands ###
