"""empty message

Revision ID: 796d8587c56d
Revises: 204e5a1c8392
Create Date: 2024-08-17 15:43:11.179180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796d8587c56d'
down_revision = '204e5a1c8392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('offer', sa.String(), nullable=True),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
